### PR TITLE
fix(client): do not add duplicate headers

### PR DESCRIPTION
**Pull request by Erk-**

### CODE REVIEW

**Comment by Erk-** [comment]
A open question here could be which headers should have priority?

**Comment by Gelbpunkt** [comment]
> A open question here could be which headers should have priority?

I think it is fair to disallow adding these headers. The problem I have with this change as-is is that it silently skips them without the user ever being told so. I'd probably prefer `add_header` to return `Result<Self, Error>` in that case.

**Review by Gelbpunkt — APPROVED** [review]
Still not sure about the associated constant, but otherwise looks fine

**Comment by Erk-** [comment]
I guess the alternative to pre-filtering your headers is just to try and add them.

**Review by vilgotf — APPROVED** [review]

**Pull request merged**
